// The vocabulary dataset to be used in the game
export const data = [
  { // unit 1
    unit: "1",
    title: "a am an",
    wordList: [
      { word: "cat", imageUrl: "../assets/images/cat.png" },
      { word: "ant", imageUrl: "../assets/images/ant.png" },
      { word: "yak", imageUrl: "../assets/images/yak.png" },
      { word: "ax", imageUrl: "../assets/images/ax.png" },
      { word: "ram", imageUrl: "../assets/images/ram.png" },
      { word: "jam", imageUrl: "../assets/images/jam.png" },
      { word: "yam", imageUrl: "../assets/images/yam.png" },
      { word: "dam", imageUrl: "../assets/images/dam.png" },
      { word: "fan", imageUrl: "../assets/images/fan.png" },
      { word: "man", imageUrl: "../assets/images/man.png" },
      { word: "pan", imageUrl: "../assets/images/pan.png" },
      { word: "can", imageUrl: "../assets/images/can.png" },
    ],
  },
  { // unit 2
    unit: "2",
    title: "ad ag ap at",
    wordList: [
      { word: "dad", imageUrl: "../assets/images/dad.png" },
      { word: "pad", imageUrl: "../assets/images/pad.png" },
      { word: "bag", imageUrl: "../assets/images/bag.png" },
      { word: "rag", imageUrl: "../assets/images/rag.png" },
      { word: "cap", imageUrl: "../assets/images/cap.png" },
      { word: "map", imageUrl: "../assets/images/map.png" },
      { word: "nap", imageUrl: "../assets/images/nap.png" },
      { word: "tap", imageUrl: "../assets/images/tap.png" },
      { word: "bat", imageUrl: "../assets/images/bat.png" },
      { word: "rat", imageUrl: "../assets/images/rat.png" },
      { word: "hat", imageUrl: "../assets/images/hat.png" },
      { word: "mat", imageUrl: "../assets/images/mat.png" },
    ],
  },
    { // unit 3
    unit: "3",
    title: "e et en ed",
    wordList: [
      { word: "web", imageUrl: "../assets/images/web.png" },
      { word: "egg", imageUrl: "../assets/images/egg.png" },
      { word: "vet", imageUrl: "../assets/images/vet.png" },
      { word: "ten", imageUrl: "../assets/images/ten.png" },
      { word: "jet", imageUrl: "../assets/images/jet.png" },
      { word: "net", imageUrl: "../assets/images/net.png" },
      { word: "wet", imageUrl: "../assets/images/wet.png" },
      { word: "pet", imageUrl: "../assets/images/pet.png" },
      { word: "hen", imageUrl: "../assets/images/hen.png" },
      { word: "pen", imageUrl: "../assets/images/pen.png" },
      { word: "red", imageUrl: "../assets/images/red.png" },
      { word: "bed", imageUrl: "../assets/images/bed.png" },
    ],
  },
    { // unit 4
    unit: "4",
    title: "i ip ib id",
    wordList: [
      { word: "hip", imageUrl: "../assets/images/hip.png" },
      { word: "ink", imageUrl: "../assets/images/ink.png" },
      { word: "zip", imageUrl: "../assets/images/zip.png" },
      { word: "in", imageUrl: "../assets/images/in.png" },
      { word: "lip", imageUrl: "../assets/images/lip.png" },
      { word: "tip", imageUrl: "../assets/images/tip.png" },
      { word: "sip", imageUrl: "../assets/images/sip.png" },
      { word: "rip", imageUrl: "../assets/images/rip.png" },
      { word: "bib", imageUrl: "../assets/images/bib.png" },
      { word: "rib", imageUrl: "../assets/images/rib.png" },
      { word: "kid", imageUrl: "../assets/images/kid.png" },
      { word: "lid", imageUrl: "../assets/images/lid.png" },
    ],
  },
    { // unit 5
    unit: "5",
    title: "in ig it ix",
    wordList: [
      { word: "pin", imageUrl: "../assets/images/pin.png" },
      { word: "fin", imageUrl: "../assets/images/fin.png" },
      { word: "bin", imageUrl: "../assets/images/bin.png" },
      { word: "win", imageUrl: "../assets/images/win.png" },
      { word: "fig", imageUrl: "../assets/images/fig.png" },
      { word: "wig", imageUrl: "../assets/images/wig.png" },
      { word: "big", imageUrl: "../assets/images/big.png" },
      { word: "dig", imageUrl: "../assets/images/dig.png" },
      { word: "pit", imageUrl: "../assets/images/pit.png" },
      { word: "hit", imageUrl: "../assets/images/hit.png" },
      { word: "six", imageUrl: "../assets/images/six.png" },
      { word: "mix", imageUrl: "../assets/images/mix.png" },
    ],
  },
    { // unit 6
    unit: "6",
    title: "o ot op",
    wordList: [
      { word: "fox", imageUrl: "../assets/images/fox.png" },
      { word: "log", imageUrl: "../assets/images/log.png" },
      { word: "ox", imageUrl: "../assets/images/ox.png" },
      { word: "rod", imageUrl: "../assets/images/rod.png" },
      { word: "pot", imageUrl: "../assets/images/pot.png" },
      { word: "hot", imageUrl: "../assets/images/hot.png" },
      { word: "cot", imageUrl: "../assets/images/cot.png" },
      { word: "dot", imageUrl: "../assets/images/dot.png" },
      { word: "top", imageUrl: "../assets/images/top.png" },
      { word: "mop", imageUrl: "../assets/images/mop.png" },
      { word: "hop", imageUrl: "../assets/images/hop.png" },
      { word: "pop", imageUrl: "../assets/images/pop.png" },
    ],
  },
    { // unit 7
    unit: "7",
    title: "u ug ud up",
    wordList: [
      { word: "sun", imageUrl: "../assets/images/sun.png" },
      { word: "up", imageUrl: "../assets/images/up.png" },
      { word: "jug", imageUrl: "../assets/images/jug.png" },
      { word: "hug", imageUrl: "../assets/images/hug.png" },
      { word: "bug", imageUrl: "../assets/images/bug.png" },
      { word: "rug", imageUrl: "../assets/images/rug.png" },
      { word: "mug", imageUrl: "../assets/images/mug.png" },
      { word: "bud", imageUrl: "../assets/images/bud.png" },
      { word: "mud", imageUrl: "../assets/images/mud.png" },
      { word: "pup", imageUrl: "../assets/images/pup.png" },
      { word: "cup", imageUrl: "../assets/images/cup.png" },
    ],
  },
    { // unit 8
    unit: "8",
    title: "ut ub um un",
    wordList: [
      { word: "nut", imageUrl: "../assets/images/nut.png" },
      { word: "hut", imageUrl: "../assets/images/hut.png" },
      { word: "cut", imageUrl: "../assets/images/cut.png" },
      { word: "cub", imageUrl: "../assets/images/cub.png" },
      { word: "tub", imageUrl: "../assets/images/tub.png" },
      { word: "gum", imageUrl: "../assets/images/gum.png" },
      { word: "hum", imageUrl: "../assets/images/hum.png" },
      { word: "bun", imageUrl: "../assets/images/bun.png" },
      { word: "run", imageUrl: "../assets/images/run.png" },
      { word: "fun", imageUrl: "../assets/images/fun.png" },
    ],
  },
]