// The vocabulary dataset to be used in the game
export const data = [
  { // unit 1
    unit: "1",
    title: "My Birthday",
    wordList: [
      { word: "present", imageUrl: "../assets/images/present.png" },
      { word: "hat", imageUrl: "../assets/images/hat.png" },
      { word: "cup", imageUrl: "../assets/images/cup.png" },
      { word: "cake", imageUrl: "../assets/images/cake.png" },
      { word: "biscuit", imageUrl: "../assets/images/biscuit.png" },
      { word: "candle", imageUrl: "../assets/images/candle.png" },
      { word: "card", imageUrl: "../assets/images/card.png" },
      { word: "sandwich", imageUrl: "../assets/images/sandwich.png" },
      { word: "plate", imageUrl: "../assets/images/plate.png" },
      { word: "balloon", imageUrl: "../assets/images/balloon.png" },
    ],
  },
  { // unit 2
    unit: "2",
    title: "My Classroom",
    wordList: [
      { word: "file", imageUrl: "../assets/images/file.png" },
      { word: "pencil", imageUrl: "../assets/images/pencil.png" },
      { word: "pen", imageUrl: "../assets/images/pen.png" },
      { word: "school bag", imageUrl: "../assets/images/school-bag.png" },
      { word: "crayon", imageUrl: "../assets/images/crayon.png" },
      { word: "notebook", imageUrl: "../assets/images/note-book.png" },
      { word: "ruler", imageUrl: "../assets/images/ruler.png" },
      { word: "pencil case", imageUrl: "../assets/images/pencil-case.png" },
      { word: "sharpener", imageUrl: "../assets/images/pencil-sharpener.png" },
      { word: "rubber", imageUrl: "../assets/images/rubber.png" },
    ],
  },
    { // unit 3
    unit: "3",
    title: "My Body",
    wordList: [
      { word: "head", imageUrl: "../assets/images/head.png" },
      { word: "mouth", imageUrl: "../assets/images/mouth.png" },
      { word: "arms", imageUrl: "../assets/images/arms.png" },
      { word: "chin", imageUrl: "../assets/images/chin.png" },
      { word: "ears", imageUrl: "../assets/images/ears.png" },
      { word: "eyes", imageUrl: "../assets/images/eyes.png" },
      { word: "fingers", imageUrl: "../assets/images/fingers.png" },
      { word: "legs", imageUrl: "../assets/images/legs.png" },
      { word: "nose", imageUrl: "../assets/images/nose.png" },
      { word: "toes", imageUrl: "../assets/images/toes.png" },
    ],
  },
    { // unit 4
    unit: "4",
    title: "My Clothes",
    wordList: [
      { word: "coat", imageUrl: "../assets/images/coat.png" },
      { word: "gloves", imageUrl: "../assets/images/gloves.png" },
      { word: "trousers", imageUrl: "../assets/images/trousers.png" },
      { word: "shirt", imageUrl: "../assets/images/shirt.png" },
      { word: "t-shirt", imageUrl: "../assets/images/t-shirt.png" },
      { word: "dress", imageUrl: "../assets/images/dress.png" },
      { word: "skirt", imageUrl: "../assets/images/skirt.png" },
      { word: "shoes", imageUrl: "../assets/images/shoes.png" },
      { word: "jumper", imageUrl: "../assets/images/jumper.png" },
      { word: "socks", imageUrl: "../assets/images/socks.png" },
    ],
  },
    { // unit 5
    unit: "5",
    title: "Food I Like",
    wordList: [
      { word: "hamburger", imageUrl: "../assets/images/hamburger.png" },
      { word: "chicken", imageUrl: "../assets/images/chicken.png" },
      { word: "chips", imageUrl: "../assets/images/chips.png" },
      { word: "salad", imageUrl: "../assets/images/salad.png" },
      { word: "pizza", imageUrl: "../assets/images/pizza.png" },
      { word: "ice cream", imageUrl: "../assets/images/ice cream.png" },
      { word: "chocolate", imageUrl: "../assets/images/chocolate.png" },
      { word: "yogurt", imageUrl: "../assets/images/yogurt.png" },
      { word: "apple", imageUrl: "../assets/images/apple.png" },
      { word: "banana", imageUrl: "../assets/images/banana.png" },
    ],
  },
    { // unit 6
    unit: "6",
    title: "My Toys",
    wordList: [
      { word: "doll", imageUrl: "../assets/images/doll.png" },
      { word: "bike", imageUrl: "../assets/images/bike.png" },
      { word: "ball", imageUrl: "../assets/images/ball.png" },
      { word: "car", imageUrl: "../assets/images/car.png" },
      { word: "train", imageUrl: "../assets/images/train.png" },
      { word: "marbles", imageUrl: "../assets/images/marbles.png" },
      { word: "skates", imageUrl: "../assets/images/skates.png" },
      { word: "plane", imageUrl: "../assets/images/plane.png" },
      { word: "robot", imageUrl: "../assets/images/robot.png" },
      { word: "computer game", imageUrl: "../assets/images/computer game.png" },
    ],
  },
    { // unit 7
    unit: "7",
    title: "My Family",
    wordList: [
      { word: "mother", imageUrl: "../assets/images/mother.png" },
      { word: "father", imageUrl: "../assets/images/hat.png" },
      { word: "brother", imageUrl: "../assets/images/brother.png" },
      { word: "sister", imageUrl: "../assets/images/sister.png" },
      { word: "aunt", imageUrl: "../assets/images/aunt.png" },
      { word: "uncle", imageUrl: "../assets/images/uncle.png" },
      { word: "cousin", imageUrl: "../assets/images/cousin.png" },
      { word: "baby", imageUrl: "../assets/images/baby.png" },
      { word: "grandfather", imageUrl: "../assets/images/grandfather.png" },
      { word: "grandmother", imageUrl: "../assets/images/grandmother.png" },
    ],
  },
    { // unit 8
    unit: "8",
    title: "My Pets",
    wordList: [
      { word: "cat", imageUrl: "../assets/images/cat.png" },
      { word: "dog", imageUrl: "../assets/images/dog.png" },
      { word: "rabbit", imageUrl: "../assets/images/rabbit.png" },
      { word: "bird", imageUrl: "../assets/images/bird.png" },
      { word: "mouse", imageUrl: "../assets/images/mouse.png" },
      { word: "hamster", imageUrl: "../assets/images/hamster.png" },
      { word: "turtle", imageUrl: "../assets/images/turtle.png" },
      { word: "pony", imageUrl: "../assets/images/pony.png" },
      { word: "fish", imageUrl: "../assets/images/fish.png" },
      { word: "guinea pig", imageUrl: "../assets/images/guinea pig.png" },
    ],
  },
    { // unit 9
    unit: "9",
    title: "Treasure!",
    wordList: [
      { word: "tree", imageUrl: "../assets/images/tree.png" },
      { word: "flower", imageUrl: "../assets/images/flower.png" },
      { word: "grass", imageUrl: "../assets/images/grass.png" },
      { word: "rock", imageUrl: "../assets/images/rock.png" },
      { word: "river", imageUrl: "../assets/images/river.png" },
      { word: "hill", imageUrl: "../assets/images/hill.png" },
      { word: "bush", imageUrl: "../assets/images/bush.png" },
      { word: "path", imageUrl: "../assets/images/path.png" },
      { word: "fence", imageUrl: "../assets/images/fence.png" },
      { word: "gate", imageUrl: "../assets/images/gate.png" },
    ],
  },
]